global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'scylla'
    static_configs:
      - targets: ['scheduler-scylla:9180']

  - job_name: 'ingestion'
    static_configs:
      - targets: ['scheduler-ingestion:8081']

  - job_name: 'picker'
    static_configs:
      - targets: ['scheduler-picker:8082']

  - job_name: 'worker'
    static_configs:
      - targets: ['scheduler-worker:8083']
